[project]
name = "campos-observados-era5"
version = "0.1.0"
description = ""
authors = [
    {name = "Bruno Capucin",email = "bruno.capucin@ampereconsultoria.com.br"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "pandas (>=3.0.1,<4.0.0)",
    "cartopy (>=0.25.0,<0.26.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "numpy (>=2.4.3,<3.0.0)",
    "scipy (>=1.17.1,<2.0.0)",
    "xarray (>=2026.2.0,<2027.0.0)",
    "netcdf4 (>=1.7.4,<2.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "paramiko (>=4.0.0,<5.0.0)",
    "dynaconf (>=3.2.12,<4.0.0)",
    "fake-headers (>=1.0.2,<2.0.0)",
    "cdsapi (>=0.7.7,<0.8.0)",
    "cfgrib (>=0.9.15.1,<0.10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
